require_relative 'commands/path'
require_relative 'commands/auth'
require_relative 'commands/sudo'
require_relative 'commands/command'
require_relative 'commands/var'
require_relative 'commands/alias'
require_relative 'commands/about'