require_relative 'helpers/password'
require_relative 'helpers/vars'
require_relative 'helpers/args'
require_relative 'helpers/display'
require_relative 'helpers/running'
require_relative 'helpers/alias'
require_relative 'helpers/about'